[package]
name = "dxh"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "dx helpers"
repository = "https://github.com/nxcy/dxh"

[dependencies.windows]
version = "0.56"
features = [
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
]
